### ISSUE TITLE
Add static banner

### ISSUE THREAD

**Issue by SaileshSriram** [PyPals/pypals-website#1]
There needs to be a simple, static banner that is up till the actual site is up. 
It should preferably include,
- Brief description of what PyPals is
- How we can be contacted
- Link to our github 
- Timeline for when we'll be up and running

We can add placeholders for now and the content will be decided the next time we meet.

**Comment by ykl7** [comment]
@SaileshSriram @d1ndra  close this issue. It has been taken care of by PR #2
