### ISSUE TITLE
Heading coming after description on mobile

### ISSUE THREAD

**Issue by d1ndra** [PyPals/pypals-website#13]
@jiteshjha On opening the website on the phone, for the topics 'Who are we?' and 'When?' the description appears before the heading.

**Comment by d1ndra** [comment]
@avikantz Issue still unresolved.

**Comment by ykl7** [comment]
@d1ndra just checked on my phone. issue is resolved

Screenshots:

![img_2781](https://cloud.githubusercontent.com/assets/4996184/18489209/3b503086-7a1a-11e6-8f57-293d7edf6d5d.PNG)
![img_2782](https://cloud.githubusercontent.com/assets/4996184/18489214/4395f8fc-7a1a-11e6-895b-962a4c055274.PNG)

**Comment by d1ndra** [comment]
@ykl7 Damn, it was showing up incorrectly some time ago on my phone. Must have been using the cached version.
