### ISSUE TITLE
api

### ISSUE THREAD

**Issue by ykl7** [PyPals/pypals-website#24]
@d1ndra 2 end points needed - 1 to store user data on registration and 1 to store qr code data (talk name) along with user's name to mark attendance.
Third endpoint can be made to fetch details of all talks, making the apps completely dynamic. This is an extra feature and can be done at the end.

**Comment by d1ndra** [comment]
@ykl7 What parameters would be posted to the various end points?

**Comment by ykl7** [comment]
@d1ndra for the attendance endpoint, need to send json with string keys username and talkname
For the registration endpoint, need to send json for data from #5 - name, registration number, email, phone, tshirt size (maybe). Other information gathered from registration form may be discarded
