### ISSUE TITLE
call for proposals page

### ISSUE THREAD

**Issue by ykl7** [PyPals/pypals-website#7]
@d1ndra @jiteshjha we need a simple page announcing call for proposals
Page will basically show bunch of guidelines and format, last date of submission and email id to send it to
Something like https://in.pycon.org/cfp/2016/proposals/

**Comment by ykl7** [comment]
@d1ndra @SaileshSriram @xoher @purak24 
Adding following guidelines for proposal:

Proposal should have a clear title and description content.
Proposal description should be brief.
Proposal should describe the target audience of the talk.
Proposal content should adhere to the prescribed code of conduct.
Selection about talks will notified via email.
For any questions, please write to contact@pypals.org.

Please ok before I send a PR.

**Comment by ykl7** [comment]
@d1ndra @SaileshSriram @xoher @purak24 
Adding following deadlines:

October 3 : Proposal submission deadline
October 7 : Talk selection announcement
October 15 : Final announcement

Please ok before I send a PR

**Comment by purak24** [comment]
Why ask for the target audience?
Selection about talks will **be** notified via email.

**Comment by ykl7** [comment]
@purak24 added the 'be'
Asked for target audience because we need to publicise it as such. Can remove that field too.

**Comment by purak24** [comment]
@ykl7 I don’t think target audience makes much sense in our case. We should remove that. @SaileshSriram what say?

**Comment by ykl7** [comment]
@purak24 will remove that. Like you said, it makes no sense in this context.
What about the rest? @SaileshSriram @xoher @d1ndra

**Comment by purak24** [comment]
@ykl7 What is "the prescribed code of conduct."?

**Comment by ykl7** [comment]
@purak24 its the PyCon standard, linked to their code of conduct itself, just a formality
